// <auto-generated />
using System;
using M.Model.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M.Model.Migrations
{
    [DbContext(typeof(MChenVipDbContext))]
    [Migration("20200328122104_Update_Table_GuidePagesMenuInfo_Fang")]
    partial class Update_Table_GuidePagesMenuInfo_Fang
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("M.Model.Entity.AccessHistoryLog", b =>
                {
                    b.Property<int>("AHId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("DeviceInfo")
                        .IsRequired();

                    b.Property<int>("IsDeleted");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("AHId");

                    b.ToTable("AccessHistoryLog");
                });

            modelBuilder.Entity("M.Model.Entity.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminName");

                    b.Property<string>("AdminPwd");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "admin",
                            AdminPwd = "123456",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 848, DateTimeKind.Local).AddTicks(7015),
                            IsDeleted = 0
                        },
                        new
                        {
                            Id = 2,
                            AdminName = "Mr.Fang",
                            AdminPwd = "Fh2269...",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 849, DateTimeKind.Local).AddTicks(4127),
                            IsDeleted = 0
                        });
                });

            modelBuilder.Entity("M.Model.Entity.BackGroundImageInfo", b =>
                {
                    b.Property<int>("BGId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BGUrl");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("IsDeleted");

                    b.HasKey("BGId");

                    b.ToTable("BackGroundImageInfo");

                    b.HasData(
                        new
                        {
                            BGId = 1,
                            BGUrl = "http://mchen.vip/assets/images/background/bg1.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(2187),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 2,
                            BGUrl = "http://mchen.vip/assets/images/background/bg2.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3111),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 3,
                            BGUrl = "http://mchen.vip/assets/images/background/bg3.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3134),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 4,
                            BGUrl = "http://mchen.vip/assets/images/background/bg4.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3144),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 5,
                            BGUrl = "http://mchen.vip/assets/images/background/bg5.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3154),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 6,
                            BGUrl = "http://mchen.vip/assets/images/background/bg6.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3164),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 7,
                            BGUrl = "http://mchen.vip/assets/images/background/bg7.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3173),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 8,
                            BGUrl = "http://mchen.vip/assets/images/background/bg8.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3182),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 9,
                            BGUrl = "http://mchen.vip/assets/images/background/bg9.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3190),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 10,
                            BGUrl = "http://mchen.vip/assets/images/background/bg10.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3200),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 11,
                            BGUrl = "http://mchen.vip/assets/images/background/bg11.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3209),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 12,
                            BGUrl = "http://mchen.vip/assets/images/background/bg12.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3218),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 13,
                            BGUrl = "http://mchen.vip/assets/images/background/bg13.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3227),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 14,
                            BGUrl = "http://mchen.vip/assets/images/background/bg14.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3235),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 15,
                            BGUrl = "http://mchen.vip/assets/images/background/bg15.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3244),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 16,
                            BGUrl = "http://mchen.vip/assets/images/background/bg16.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3252),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 17,
                            BGUrl = "http://mchen.vip/assets/images/background/bg17.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3261),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 18,
                            BGUrl = "http://mchen.vip/assets/images/background/bg18.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3308),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 19,
                            BGUrl = "http://mchen.vip/assets/images/background/bg19.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3318),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 20,
                            BGUrl = "http://mchen.vip/assets/images/background/bg20.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3326),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 21,
                            BGUrl = "http://mchen.vip/assets/images/background/bg21.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3335),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 22,
                            BGUrl = "http://mchen.vip/assets/images/background/bg22.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3343),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 23,
                            BGUrl = "http://mchen.vip/assets/images/background/bg23.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3352),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 24,
                            BGUrl = "http://mchen.vip/assets/images/background/bg24.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3361),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 25,
                            BGUrl = "http://mchen.vip/assets/images/background/bg25.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3369),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 26,
                            BGUrl = "http://mchen.vip/assets/images/background/bg26.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3378),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 27,
                            BGUrl = "http://mchen.vip/assets/images/background/bg27.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3386),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 28,
                            BGUrl = "http://mchen.vip/assets/images/background/bg28.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3395),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 29,
                            BGUrl = "http://mchen.vip/assets/images/background/bg29.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3404),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 30,
                            BGUrl = "http://mchen.vip/assets/images/background/bg30.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3413),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 31,
                            BGUrl = "http://mchen.vip/assets/images/background/bg31.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3421),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 32,
                            BGUrl = "http://mchen.vip/assets/images/background/bg32.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3430),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 33,
                            BGUrl = "http://mchen.vip/assets/images/background/bg33.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3439),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 34,
                            BGUrl = "http://mchen.vip/assets/images/background/bg34.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3448),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 35,
                            BGUrl = "http://mchen.vip/assets/images/background/bg35.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3457),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 36,
                            BGUrl = "http://mchen.vip/assets/images/background/bg36.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3465),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 37,
                            BGUrl = "http://mchen.vip/assets/images/background/bg37.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3531),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 38,
                            BGUrl = "http://mchen.vip/assets/images/background/bg38.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3540),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 39,
                            BGUrl = "http://mchen.vip/assets/images/background/bg39.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3548),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 40,
                            BGUrl = "http://mchen.vip/assets/images/background/bg40.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3557),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 41,
                            BGUrl = "http://mchen.vip/assets/images/background/bg41.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3566),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 42,
                            BGUrl = "http://mchen.vip/assets/images/background/bg42.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3574),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 43,
                            BGUrl = "http://mchen.vip/assets/images/background/bg43.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3583),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 44,
                            BGUrl = "http://mchen.vip/assets/images/background/bg44.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3591),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 45,
                            BGUrl = "http://mchen.vip/assets/images/background/bg45.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3600),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 46,
                            BGUrl = "http://mchen.vip/assets/images/background/bg46.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3608),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 47,
                            BGUrl = "http://mchen.vip/assets/images/background/bg47.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3617),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 48,
                            BGUrl = "http://mchen.vip/assets/images/background/bg48.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3625),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 49,
                            BGUrl = "http://mchen.vip/assets/images/background/bg49.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3634),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 50,
                            BGUrl = "http://mchen.vip/assets/images/background/bg50.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3642),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 51,
                            BGUrl = "http://mchen.vip/assets/images/background/bg51.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3651),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 52,
                            BGUrl = "http://mchen.vip/assets/images/background/bg52.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3659),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 53,
                            BGUrl = "http://mchen.vip/assets/images/background/bg53.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3668),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 54,
                            BGUrl = "http://mchen.vip/assets/images/background/bg54.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3676),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 55,
                            BGUrl = "http://mchen.vip/assets/images/background/bg55.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3685),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 56,
                            BGUrl = "http://mchen.vip/assets/images/background/bg56.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3694),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 57,
                            BGUrl = "http://mchen.vip/assets/images/background/bg57.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3732),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 58,
                            BGUrl = "http://mchen.vip/assets/images/background/bg58.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3741),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 59,
                            BGUrl = "http://mchen.vip/assets/images/background/bg59.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3750),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 60,
                            BGUrl = "http://mchen.vip/assets/images/background/bg60.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3758),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 61,
                            BGUrl = "http://mchen.vip/assets/images/background/bg61.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3767),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 62,
                            BGUrl = "http://mchen.vip/assets/images/background/bg62.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3775),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 63,
                            BGUrl = "http://mchen.vip/assets/images/background/bg63.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3784),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 64,
                            BGUrl = "http://mchen.vip/assets/images/background/bg64.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3793),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 65,
                            BGUrl = "http://mchen.vip/assets/images/background/bg65.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3801),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 66,
                            BGUrl = "http://mchen.vip/assets/images/background/bg66.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3811),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 67,
                            BGUrl = "http://mchen.vip/assets/images/background/bg67.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3820),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 68,
                            BGUrl = "http://mchen.vip/assets/images/background/bg68.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3828),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 69,
                            BGUrl = "http://mchen.vip/assets/images/background/bg69.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3837),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 70,
                            BGUrl = "http://mchen.vip/assets/images/background/bg70.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3855),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 71,
                            BGUrl = "http://mchen.vip/assets/images/background/bg71.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3864),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 72,
                            BGUrl = "http://mchen.vip/assets/images/background/bg72.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3872),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 73,
                            BGUrl = "http://mchen.vip/assets/images/background/bg73.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3881),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 74,
                            BGUrl = "http://mchen.vip/assets/images/background/bg74.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3955),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 75,
                            BGUrl = "http://mchen.vip/assets/images/background/bg75.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3966),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 76,
                            BGUrl = "http://mchen.vip/assets/images/background/bg76.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3975),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 77,
                            BGUrl = "http://mchen.vip/assets/images/background/bg77.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3984),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 78,
                            BGUrl = "http://mchen.vip/assets/images/background/bg78.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(3992),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 79,
                            BGUrl = "http://mchen.vip/assets/images/background/bg79.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4000),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 80,
                            BGUrl = "http://mchen.vip/assets/images/background/bg80.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4009),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 81,
                            BGUrl = "http://mchen.vip/assets/images/background/bg81.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4017),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 82,
                            BGUrl = "http://mchen.vip/assets/images/background/bg82.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4026),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 83,
                            BGUrl = "http://mchen.vip/assets/images/background/bg83.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4034),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 84,
                            BGUrl = "http://mchen.vip/assets/images/background/bg84.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4043),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 85,
                            BGUrl = "http://mchen.vip/assets/images/background/bg85.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4052),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 86,
                            BGUrl = "http://mchen.vip/assets/images/background/bg86.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4060),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 87,
                            BGUrl = "http://mchen.vip/assets/images/background/bg87.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4068),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 88,
                            BGUrl = "http://mchen.vip/assets/images/background/bg88.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4077),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 89,
                            BGUrl = "http://mchen.vip/assets/images/background/bg89.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4085),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 90,
                            BGUrl = "http://mchen.vip/assets/images/background/bg90.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4094),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 91,
                            BGUrl = "http://mchen.vip/assets/images/background/bg91.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4102),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 92,
                            BGUrl = "http://mchen.vip/assets/images/background/bg92.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4111),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 93,
                            BGUrl = "http://mchen.vip/assets/images/background/bg93.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4119),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 94,
                            BGUrl = "http://mchen.vip/assets/images/background/bg94.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4156),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 95,
                            BGUrl = "http://mchen.vip/assets/images/background/bg95.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4166),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 96,
                            BGUrl = "http://mchen.vip/assets/images/background/bg96.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4175),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 97,
                            BGUrl = "http://mchen.vip/assets/images/background/bg97.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4183),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 98,
                            BGUrl = "http://mchen.vip/assets/images/background/bg98.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4192),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 99,
                            BGUrl = "http://mchen.vip/assets/images/background/bg99.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4200),
                            IsDeleted = 0
                        },
                        new
                        {
                            BGId = 100,
                            BGUrl = "http://mchen.vip/assets/images/background/bg100.jpg",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4209),
                            IsDeleted = 0
                        });
                });

            modelBuilder.Entity("M.Model.Entity.CopywritingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("CopywritingInfo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "当你的能力还撑不起你的野心的时，你就需要静下心来 好好学习。",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(4692),
                            IsDeleted = 0
                        },
                        new
                        {
                            Id = 2,
                            Content = "脏的人多了，干净反倒成了一种错。",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(5423),
                            IsDeleted = 0
                        },
                        new
                        {
                            Id = 3,
                            Content = "你羡慕的生活都是你没熬过的苦。",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(5431),
                            IsDeleted = 0
                        },
                        new
                        {
                            Id = 4,
                            Content = "所谓天才，只不过是把别人喝咖啡的功夫都用在了工作上了。",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(5431),
                            IsDeleted = 0
                        },
                        new
                        {
                            Id = 5,
                            Content = "生活便是寻求新的知识。——门捷列夫",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(5432),
                            IsDeleted = 0
                        },
                        new
                        {
                            Id = 6,
                            Content = "如果你浪费了自己的年龄，那是挺可悲的。因为你的青春只能持续一点儿时间——很短的一点儿时间。",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(5433),
                            IsDeleted = 0
                        },
                        new
                        {
                            Id = 7,
                            Content = "世界上一成不变的东西，只有“任何事物都是在不断变化的”这条真理。",
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(5433),
                            IsDeleted = 0
                        });
                });

            modelBuilder.Entity("M.Model.Entity.DevLoveInfo", b =>
                {
                    b.Property<int>("DLId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("DLDay")
                        .IsRequired();

                    b.Property<string>("DLInfo")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("DLMonth")
                        .IsRequired();

                    b.Property<string>("DLName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("DLQQ")
                        .IsRequired();

                    b.Property<string>("DLYear")
                        .IsRequired();

                    b.Property<string>("DLoveInfo")
                        .HasMaxLength(10);

                    b.Property<string>("DLoveName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("IsDeleted");

                    b.HasKey("DLId");

                    b.ToTable("DevLoveInfo");

                    b.HasData(
                        new
                        {
                            DLId = 1,
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 849, DateTimeKind.Local).AddTicks(6013),
                            DLDay = "6",
                            DLInfo = "希望以后和你的生活，温柔，有趣，不必太激烈，三餐，四季，不必太匆忙，毕竟我有一生的时间要和你浪费。",
                            DLMonth = "3",
                            DLName = "Mr.Fang",
                            DLQQ = "2875616188",
                            DLYear = "2017",
                            DLoveInfo = "我永远在！",
                            DLoveName = "文洁",
                            IsDeleted = 0
                        });
                });

            modelBuilder.Entity("M.Model.Entity.EmailHistoryInfo", b =>
                {
                    b.Property<int>("EHID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("EmailBody")
                        .IsRequired();

                    b.Property<int>("IsDeleted");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.HasKey("EHID");

                    b.ToTable("EmailHistoryInfo");
                });

            modelBuilder.Entity("M.Model.Entity.GuidePagesMenuInfo", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("IsDeleted");

                    b.Property<string>("MenuName")
                        .IsRequired();

                    b.Property<int>("MenuOrder");

                    b.Property<string>("MenuUrl")
                        .IsRequired();

                    b.Property<int>("ParentId");

                    b.HasKey("MenuID");

                    b.ToTable("GuidePagesMenuInfo");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(22),
                            IsDeleted = 0,
                            MenuName = "首页",
                            MenuOrder = 1,
                            MenuUrl = "https://home.mchen.vip",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 2,
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(1459),
                            IsDeleted = 0,
                            MenuName = "QQ",
                            MenuOrder = 2,
                            MenuUrl = "https://wpa.qq.com/msgrd?v=3&uin=2875616188&site=qq&menu=yes",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 3,
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(1472),
                            IsDeleted = 0,
                            MenuName = "微信",
                            MenuOrder = 3,
                            MenuUrl = "https://mchen.vip/accsets/images/weixin.jpg",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 4,
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(1473),
                            IsDeleted = 0,
                            MenuName = "Mr.Fang♥Mrs.Zhou",
                            MenuOrder = 4,
                            MenuUrl = "https://fh.mchen.vip",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 5,
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(1474),
                            IsDeleted = 0,
                            MenuName = "表白小工具",
                            MenuOrder = 5,
                            MenuUrl = "https://devlove.mchen.vip",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 6,
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(1475),
                            IsDeleted = 0,
                            MenuName = "实用小工具",
                            MenuOrder = 6,
                            MenuUrl = "https://tool.mchen.vip",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 7,
                            CreateTime = new DateTime(2020, 3, 28, 20, 21, 3, 850, DateTimeKind.Local).AddTicks(1475),
                            IsDeleted = 0,
                            MenuName = "休闲小游戏",
                            MenuOrder = 7,
                            MenuUrl = "https://game.mchen.vip",
                            ParentId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
