// <auto-generated />
using System;
using M.Model.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M.Model.Migrations
{
    [DbContext(typeof(MChenVipDbContext))]
    [Migration("20200325110806_Add_Table_AccessHistoryLog")]
    partial class Add_Table_AccessHistoryLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("M.Model.Entity.AccessHistoryLog", b =>
                {
                    b.Property<int>("AHId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("IsDeleted");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.HasKey("AHId");

                    b.ToTable("AccessHistoryLog");
                });

            modelBuilder.Entity("M.Model.Entity.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdminName");

                    b.Property<string>("AdminPwd");

                    b.HasKey("Id");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminName = "admin",
                            AdminPwd = "123456"
                        },
                        new
                        {
                            Id = 2,
                            AdminName = "Mr.Fang",
                            AdminPwd = "Fh2269..."
                        });
                });

            modelBuilder.Entity("M.Model.Entity.DevLoveInfo", b =>
                {
                    b.Property<int>("DLId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("DLDay")
                        .IsRequired();

                    b.Property<string>("DLInfo")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("DLMonth")
                        .IsRequired();

                    b.Property<string>("DLName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("DLQQ")
                        .IsRequired();

                    b.Property<string>("DLYear")
                        .IsRequired();

                    b.Property<string>("DLoveInfo")
                        .HasMaxLength(10);

                    b.Property<string>("DLoveName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("IsDeleted");

                    b.HasKey("DLId");

                    b.ToTable("DevLoveInfo");

                    b.HasData(
                        new
                        {
                            DLId = 1,
                            CreateTime = new DateTime(2020, 3, 25, 19, 8, 6, 514, DateTimeKind.Local).AddTicks(3887),
                            DLDay = "6",
                            DLInfo = "希望以后和你的生活，温柔，有趣，不必太激烈，三餐，四季，不必太匆忙，毕竟我有一生的时间要和你浪费。",
                            DLMonth = "3",
                            DLName = "Mr.Fang",
                            DLQQ = "2875616188",
                            DLYear = "2017",
                            DLoveInfo = "我永远在！",
                            DLoveName = "文洁",
                            IsDeleted = 0
                        });
                });

            modelBuilder.Entity("M.Model.Entity.EmailHistoryInfo", b =>
                {
                    b.Property<int>("EHID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("EmailBody")
                        .IsRequired();

                    b.Property<int>("IsDeleted");

                    b.Property<string>("RecipientId")
                        .IsRequired();

                    b.HasKey("EHID");

                    b.ToTable("EmailHistoryInfo");
                });

            modelBuilder.Entity("M.Model.Entity.GuidePagesMenuInfo", b =>
                {
                    b.Property<int>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("IsDeleted");

                    b.Property<string>("MenuName")
                        .IsRequired();

                    b.Property<int>("MenuOrder");

                    b.Property<string>("MenuUrl")
                        .IsRequired();

                    b.Property<int>("ParentId");

                    b.HasKey("MenuID");

                    b.ToTable("GuidePagesMenuInfo");

                    b.HasData(
                        new
                        {
                            MenuID = 1,
                            CreateTime = new DateTime(2020, 3, 25, 19, 8, 6, 515, DateTimeKind.Local).AddTicks(3640),
                            IsDeleted = 0,
                            MenuName = "首页",
                            MenuOrder = 1,
                            MenuUrl = "http://home.mchen.vip",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 2,
                            CreateTime = new DateTime(2020, 3, 25, 19, 8, 6, 515, DateTimeKind.Local).AddTicks(4986),
                            IsDeleted = 0,
                            MenuName = "Mr.Fang♥Mrs.Zhou",
                            MenuOrder = 2,
                            MenuUrl = "http://fh.mchen.vip",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 3,
                            CreateTime = new DateTime(2020, 3, 25, 19, 8, 6, 515, DateTimeKind.Local).AddTicks(5000),
                            IsDeleted = 0,
                            MenuName = "QQ",
                            MenuOrder = 3,
                            MenuUrl = "https://wpa.qq.com/msgrd?v=3&uin=2875616188&site=qq&menu=yes",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 4,
                            CreateTime = new DateTime(2020, 3, 25, 19, 8, 6, 515, DateTimeKind.Local).AddTicks(5001),
                            IsDeleted = 0,
                            MenuName = "微信",
                            MenuOrder = 4,
                            MenuUrl = "http://mchen.vip/accsets/images/weixin.jpg",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 5,
                            CreateTime = new DateTime(2020, 3, 25, 19, 8, 6, 515, DateTimeKind.Local).AddTicks(5002),
                            IsDeleted = 0,
                            MenuName = "表白小工具",
                            MenuOrder = 5,
                            MenuUrl = "http://devlove.mchen.vip",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 6,
                            CreateTime = new DateTime(2020, 3, 25, 19, 8, 6, 515, DateTimeKind.Local).AddTicks(5003),
                            IsDeleted = 0,
                            MenuName = "实用小工具",
                            MenuOrder = 6,
                            MenuUrl = "http://tool.mchen.vip",
                            ParentId = 0
                        },
                        new
                        {
                            MenuID = 7,
                            CreateTime = new DateTime(2020, 3, 25, 19, 8, 6, 515, DateTimeKind.Local).AddTicks(5004),
                            IsDeleted = 0,
                            MenuName = "休闲小游戏",
                            MenuOrder = 7,
                            MenuUrl = "http://game.mchen.vip",
                            ParentId = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
